# Generated by Django 6.0.1 on 2026-01-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_time",
            field=models.IntegerField(default=0, help_text="Estimated time in hours"),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3
            ),
        ),
    ]
